name: AdvancedReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
authors:
    - Jumper251
    - ShallowAi
depend: [ProtocolLib]
softdepend:
  - SimpleORM
commands:
  replay:
    description: Main Replay command
    aliases: [rp]
    permission: replay.command